name: CI

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Install Dropbox
      run: brew cask install dropbox
    - name: Make tarball
      run: tar -c -v -C /Applications -f Dropbox.app.tar.gz Dropbox.app
    - uses: actions/upload-artifact@master
      with:
        name: out
        path: Dropbox.app.tar.gz
