name: Firefox

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Pull source
      uses: actions/checkout@v1
    - name: Install Firefox
      run: brew cask install firefox
    - name: Make tarball
      run: tar -c -v -C /Applications -f Firefox.app.tar.gz Firefox.app
    - name: Upload to release
      run: ./upload.sh Firefox.app.tar.gz application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
