name: GIMP

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Install Gimp
      run: brew cask install gimp
    - name: Rename .app
      run: mv /Applications/GIMP-*.app /Applications/GIMP.app
    - name: Make tarball
      run: tar -c -v -C /Applications -f GIMP.app.tar.gz GIMP.app
    - uses: actions/upload-artifact@master
      with:
        name: out
        path: GIMP.app.tar.gz
