name: GIMP

on: release

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Pull source
      uses: actions/checkout@v1
    - name: Install Gimp
      run: brew cask install gimp
    - name: Rename .app
      run: mv /Applications/GIMP-*.app /Applications/GIMP.app
    - name: Make tarball
      run: tar -c -v -C /Applications -f GIMP.app.tar.gz GIMP.app
    - name: Upload to release
      run: ./upload.sh GIMP.app.tar.gz application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
